name = "olymp-notes-bots"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "olymp-notes-stats"
database_id = "9583be4d-5f88-46ee-84e2-2a4765709155"

[vars]
SITE_URL = "https://vmaiorov-collab.github.io/olymp-notes/"
